version: '3.x'
services:
  wkchallenge-db:
    container_name: wkchallenge-db
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: wkchallenge-db
    volumes:
      - wkchallenge-data:/var/lib/postgresql/data
    networks:
      - wkchallenge-network
    ports:
      - '5432:5432'

volumes:
  wkchallenge-data:
    name: wkchallenge-data
networks:
  wkchallenge-network:
    name: wkchallenge-network
